#!/bin/bash

# ensure pikaur AUR helper is installed
if ! which pikaur; then
    sudo pacman -Syu --needed base-devel git
    cd /tmp
    git clone https://aur.archlinux.org/pikaur.git
    cd pikaur
    makepkg -fsri --noconfirm
fi

# install things that need to exist not to break configs
pikaur -Syu --needed --noconfirm - < ~/.config/yadm/packages

# set up apparmor (for increased security with firejail)
sudo sed -i  's/GRUB_CMDLINE_LINUX=""/GRUB_CMDLINUX_LINUX="lsm=lockdown,yama,apparmor,bpf"/' /etc/default/grub
sudo grub-mkconfig -o /boot/grub/grub.cfg

# add hubbe user to useful usergroups
# adm,plugdev,input,wheel for easy access to inputs and general "admin" stuff
# kvm,libvirt for libvirt KVM virtualization
# audio,realtime for real-time audio privileges
sudo usermod -aG adm,audio,input,kvm,libvirt,plugdev,realtime,wheel hubbe

# set up libvirt & virt-manager for KVM virtualization
sudo systemctl enable --now libvirtd.service
sudo systemctl start virtlogd.service

# set up rootless buildah & rootless podman
echo "kernel.unprivileged_userns_clone = 1" | sudo tee /etc/sysctl.d/10-rootless-podman.conf
sudo sysctl --system > /dev/null
sudo touch /etc/subuid /etc/subgid
sudo usermod --add-subuids 100000-165536 --add-subgids 100000-165536 hubbe

# enable profile-sync-daemon for firefox tmpfs profile sync
echo "hubbe ALL=(ALL:ALL) NOPASSWD: /usr/bin/psd-overlay-helper" | sudo tee /etc/sudoers.d/hubbe
systemctl user enable --now psd.service
