#!/bin/bash
set -e

PS3='Please choose GPU type for hardware video acceleration (VAAPI)'
options=("AMD", "Nvidia", "Intel")
select gpu in "${options[@]}"
do
    case $gpu in
        "AMD")
            $vaapi="libva-mesa-driver mesa-vdpau lib32-libva-mesa-driver lib32-mesa-vdpau"
            $vulkan="vulkan-radeon lib32-vulkan-radeon vulkan-icd-loader lib32-vulkan-icd-loader"
            ;;
        "Nvidia")
            $vaapi="nvidia-utils lib32-nvidia-utils"
            $vulkan="vulkan-icd-loader lib32-vulkan-icd-loader"
            ;;
        "Intel")
            $vaapi="intel-media-driver linux-firmware"
            $vulkan="vulkan-intel lib32-vulkan-intel vulkan-icd-loader lib32-vulkan-icd-loader"
            ;;
        *) echo "Invalid option $REPLY";;
    esac
done


# ensure pikaur AUR helper is installed
if ! which pikaur; then
    sudo pacman -Syu --needed base-devel git
    cd /tmp
    git clone https://aur.archlinux.org/pikaur.git
    cd pikaur
    makepkg -fsri --noconfirm
fi

# set up chaotic-aur
sudo pacman-key --recv-key FBA220DFC880C036 --keyserver keyserver.ubuntu.com
sudo pacman-key --lsign-key FBA220DFC880C036
sudo pacman -U 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-keyring.pkg.tar.zst' 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-mirrorlist.pkg.tar.zst'
sudo tee -a /etc/pacman.conf > /dev/null <<EOT
[chaotic-aur]
Include = /etc/pacman.d/chaotic-mirrorlist 
EOT
pikaur -Sy

# install VAAPI and Vulkan drivers
pikaur -Syu --needed $vaapi $vulkan

# install packages
$pkglist = $(cat ~/.config/yadm/packages)
pikaur -Syu --needed $pkglist

# set up apparmor auto-loading
# TODO: set kernel cmdline params for apparmor module
sudo systemctl enable apparmor.service

# add user to useful usergroups
# adm,input,wheel for easy access to inputs and general "admin" stuff
# kvm,libvirt for libvirt KVM virtualization
# audio,realtime for real-time audio privileges
# adbusers for android debug bridge access
sudo usermod -aG adbusers,adm,audio,input,kvm,libvirt,realtime,wheel $USER

# set up libvirt & virt-manager for KVM virtualization
sudo systemctl enable --now libvirtd.service
sudo systemctl start virtlogd.service

# set up rootless buildah & rootless podman
echo "kernel.unprivileged_userns_clone = 1" | sudo tee /etc/sysctl.d/10-rootless-podman.conf
sudo sysctl --system > /dev/null
sudo touch /etc/subuid /etc/subgid
sudo usermod --add-subuids 100000-165536 --add-subgids 100000-165536 $USER
