plugins: badfiles convert edit fetchart mbsync missing replaygain rewrite zero
directory: /mnt/array/Music
library: library.blb
art_filename: folder
threaded: yes
original_date: yes
per_disc_numbering: yes
asciify_paths: yes
paths:
    default: $albumartist/$original_year-$album%aunique{}/$disc.$track - $title

import:
    write: yes
    copy: yes
    move: no
    resume: ask
    incremental: yes
    quiet_fallback: skip
    timid: no

# plugins configuration
convert:
    copy_album_art: no
    dest: /mnt/array/Sync
    embed: yes
    format: opus
    never_convert_lossy_files: no
    formats:
        opus:
            command: ffmpeg -i $source -c:a libopus -b:a 64k -af aresample=resampler=soxr -ar 48000 -vn $dest
            extension: ogg

fetchart:
    auto: yes

replace:
    '^\.': _
    '[\x00-\x1f]': _
    '[<>:"\?\*\|]': _
    '[\xE8-\xEB]': e
    '[\xEC-\xEF]': i
    '[\xE2-\xE6]': a
    '[\xF2-\xF6]': o
    '[\xF8]': o
    '\.$': _
    '\s+$': ''

replaygain:
    auto: yes
    backend: gstreamer

rewrite:
    artist Tarja Turunen: Tarja
    artist Within Temptation.*: Within Temptation

zero:
    auto: yes
    fields: comments
    update_database: true
