plugins: badfiles convert edit fetchart mbsync missing replaygain rewrite
directory: /mnt/array/Music
library: library.blb                # store metadata in SQLite file in .config/beets folder
art_filename: folder                # name album cover art file "folder.ext"
threaded: yes                       # use threads
original_date: yes                  # use original album release date rather than selected version release date (for re-releases and the like)
per_disc_numbering: yes             # number tracks starting from 1 on each disc
asciify_paths: yes                  # convert all non-ASCII characters in paths to ASCII equivalents.
paths:
    default: $albumartist/$original_year-$album%aunique{}/$disc.$track - $title

import:
    write: yes                      # write metadata tags to files on import
    copy: yes                       # copy files to library directory on import
    move: no                        # don't move them
    resume: ask                     # ask before resuming
    incremental: yes                # record imported directories, so we can resume big imports if we're interrupted
    quiet_fallback: skip            # in quiet mode, skip albums if there's no strong match
    timid: no                       # don't ask for confirmation if there's a strong match

# plugins configuration
convert:
    copy_album_art: yes             # copy album art file to dest
    dest: /mnt/array/Sync
    embed: yes                      # embed album art when transcoding
    format: opus                    # use opus (see below)
    never_convert_lossy_files: no   # convert non-FLACs as well
    formats:
        opus:
            command: ffmpeg -i $source -c:a libopus -b:a 64k -af aresample=resampler=soxr -ar 48000 -vn $dest
            extension: ogg

fetchart:
    auto: yes                       # automatically download album cover art during import

replaygain:
    auto: yes                       # automatically scan and apply replaygain tags on import
    backend: ffmpeg

rewrite:                            # some artists use kinda funky names sometimes, standardize top-level directory structure
    artist Tarja Turunen: Tarja
    artist Within Temptation.*: Within Temptation
